### ISSUE TITLE
Discuss: Support for vanilla kubernetes as mgmt cluster

### ISSUE THREAD

**Issue by rmohr** [openshift/hypershift#590]
This is a tracker/discussion bug about how to enable and support vanilla kubernetes as mgmt cluster.

## Scope

There exist two possible scopes:
 * best-effort usage for development purposes (e.g. for a KubeVirt platform)
 * making this an official scenario which requires testing as usual

## Here technical steps which I could identify as necessary:

 - [x] Make route watching optional (#584, #604)
 - [x] Make the None platform pass reconciliations successful (#585)
 - [x] Promote the None platform to be available via `hypershift create cluster none` to have an easy way to run a control-plane on vanilla k8s (#630)
 - [ ] Make monitoring integration optional with autodetection during runtime?
 - [x] e2e tests on vanilla kubernetes with the None platform in openshift-ci or [kubevirt-ci](https://prow.ci.kubevirt.io/)? (#664)
