### ISSUE TITLE
Discuss: Adding a KubeVirt Management Platform

### ISSUE THREAD

**Issue by rmohr** [openshift/hypershift#591]
A few people from [KubeVirt](https://github.com/kubevirt/kubevirt) would be happy to explore adding a kubevirt platform to hypershift. I would be happy to get some feedback if that is welcome.

If so, here the steps I could identify which would probably need to be addressed:

### hypershift binary

 - [x] Move `aws` create behind `hypershift create cluster aws` and `hypershift destroy cluster aws` (#630) 
 - [x] Add a `kubevirt` provider: `hypershift create cluster kubevirt` (#779)

### controller binaries
 - [x] Refactor `aws` capi provision to make `capi` available for other platforms (#719)
 - [x] Add the KubeVirt platform using this `capi` provider: https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt (#779)
 
### testing

 - [ ] Test the KubeVirt platform with openshift virtualization (openshifts included kubevirt) in openshift-ci
 - [ ] Test the KubeVirt platform in kubevirt-ci?

**Comment by aelbarkani** [comment]
If this is achieved, OpenShift would be a 100% hyperconverged infrastructure. So clearly +1 !
I'm seeing [here](https://github.com/openshift/installer/pull/5301) though a decision to drop support for KubeVirt in OpenShift installer. Also [this ](https://github.com/openshift/cluster-api-provider-kubevirt) repo doesn't seem to be maintained, so hopefully we can have more insights from Redhat team on the roadmap about KubeVirt support :).

**Comment by fabiand** [comment]
We want to build the right approach to bring up tenant clusters. And the two links you have provided above illustrate a previous exploration.

**Comment by aelbarkani** [comment]
Hi @fabiand ! Thanks for your answer. If you have more information about why KubeVirt wasn't a good idea for this purpose I'm interested !

**Comment by rmohr** [comment]
A first WIP PR by @nirarg finally exists: #779

**Comment by rmohr** [comment]
#779 just merged. We still have to secure our progress with CI and testing and work on official capik providers, ... but basic functionality exists.
