### ISSUE TITLE
Platform AWS Controller for Hypershift provisioning

### ISSUE THREAD

**Issue by jnpacker** [openshift/hypershift#674]
# Problem
To provision Hypershift, it would be useful to have a kubernetes API approach for provisioning Hypershift HostedClusters on the ManagementCluster.

# Prototype 1
Wrap the Go code from the Hypershift CLI, while still maintaining the CLI capability to configure the required AWS infrastructure.  This was done by linking a controller reconcile loop to the HostedClusters kind.  It also leverages an AWS Credentials and  OpenShift Pull-Secret as kubernetes secrets.

**Comment by jnpacker** [comment]
## Prototype 1
Working code can be found here: https://github.com/jnpacker/hypershift/tree/platform-aws-controller/examples/cluster-demo

### Todo
* Need to separate HostedCluster and NodePool provisioning, the user/console should create both resources individually
* Need to add the AWS Provider Credential reference to HostedCluster
* Need to determine if the route53 us-east-1 relationship is for a reason. @csrwng answered this question, "Global resource, works best with us-east-1"

### Questions to be answered (Design decisions)
* How to run the controller
  * Should this be in the existing HostedCluster controller (not now as it runs to long for each create/destroy)
  * If run as a separate controller, use 1 or 2 workers.  2 is better, but deletes can still cause queueing as the operation is 60+s
    * Deletes are very slow 60+ seconds
    * Create is < 30 seconds
  * Could use the controller to spawn jobs for create/delete (introduces a lot of management overhead)
  * Could run 2x Create controllers and 1x Delete controller (gives known use of resources, can use the same binary with a param switch, treats delete, more like a garbage collection queue)
* Need to store the securityGroup on the HostedCluster so it will be available for the FIRST NodePool. Currently if not provided it tries to read this from the Default (FIRST) NodePool.

**Comment by jnpacker** [comment]
Met with the team MON NOV, 15, 2021
* Move forward with the Job approach
* Break the nodePool off
* Create a Platform resource to see what it looks like compared to the hostedClusters, can it be 1x Platform TO MANY HostedClusters??
* Split the access control, can one account be used to provision control plane and one account be used to provision the workerPlane

**Comment by jnpacker** [comment]
## Prototype 2
- [x] Disconnected nodepool and hostedcluster provisioning, so you need to create those two resources
- [x] Created a ProviderPlatform resource that contains all the AWS related goodies, and creates them if they are missing
- [x] ~Dropping the job idea, as the AWS pieces for now are fast enough~
- [ ] Teach the HostedCluster and NodePool controllers to read values from the ProviderPlatform resource.

Prototype is working except for the last step.
You can copy the details from ProviderPlatform to HostedCluster and NodePool and it will work.
https://github.com/jnpacker/hypershift/tree/add-platform-type

**Comment by jnpacker** [comment]
It was decided after further review with the team, that a platform was not the approach they wanted to take.  We will revisit this in a few weeks once more Platforms are on board.  For the time being I will close this out.

The work was refactored and is being used in ACM to support the push one button use story (create infra and Hypershift HostedCluster).  It can be found here: https://github.com/jnpacker/hypershift-curator-controller
